package auth

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// KeyType represents the kind of principal a key authenticates.
type KeyType string

const (
	KeyTypeMerchant KeyType = "merchant"
	KeyTypeAgent    KeyType = "agent"
)

const (
	// API key prefixes. All keys follow the format: <prefix><8-char hex keyID>_<32-char hex random>.
	//
	// KeyPrefixLive is the original merchant prefix kept for backward compatibility — accepted
	// by ValidateAPIKeyFormat indefinitely but never freshly generated by GenerateAPIKey.
	// New merchant keys use KeyPrefixMerchants; new agent keys use KeyPrefixAgents.
	//
	// V2 hook: when test mode is added, also accept "sg_merchants_test_" and "sg_agents_test_"
	// (absence of _test_ in the new prefixes implies live, mirroring Stripe's older pattern).
	KeyPrefixLive      = "sg_live_"
	KeyPrefixMerchants = "sg_merchants_"
	KeyPrefixAgents    = "sg_agents_"

	KeyIDLength     = 8
	KeyRandomLength = 32
)

// GenerateAPIKey generates a new API key with embedded key_id like GitHub.
// Returns the full key and the key_id.
//
// keyType determines the prefix:
//   - KeyTypeMerchant → "sg_merchants_"
//   - KeyTypeAgent    → "sg_agents_"
//
// Legacy "sg_live_" keys are never generated by this function but remain accepted by
// ValidateAPIKeyFormat for backward compatibility.
func GenerateAPIKey(keyType KeyType) (string, string, error) {
	prefix, err := prefixForKeyType(keyType)
	if err != nil {
		return "", "", err
	}

	// Generate 8-char key ID for database lookup (4 bytes -> 8 hex chars)
	keyIDBytes := make([]byte, KeyIDLength/2)
	if _, err := rand.Read(keyIDBytes); err != nil {
		return "", "", fmt.Errorf("failed to generate key ID: %w", err)
	}
	keyID := hex.EncodeToString(keyIDBytes)

	// Generate 32 random bytes for the secret portion
	randomBytes := make([]byte, KeyRandomLength/2)
	if _, err := rand.Read(randomBytes); err != nil {
		return "", "", fmt.Errorf("failed to generate random key: %w", err)
	}
	randomStr := hex.EncodeToString(randomBytes)

	// Construct full key: prefix + keyID + randomStr
	fullKey := prefix + keyID + "_" + randomStr
	return fullKey, keyID, nil
}

// prefixForKeyType returns the prefix string for a given KeyType.
// Note: KeyPrefixLive is intentionally not returned — legacy keys are validated but
// never freshly generated.
func prefixForKeyType(t KeyType) (string, error) {
	switch t {
	case KeyTypeMerchant:
		return KeyPrefixMerchants, nil
	case KeyTypeAgent:
		return KeyPrefixAgents, nil
	default:
		return "", fmt.Errorf("unknown key type: %q", t)
	}
}

// detectPrefix returns the matching known prefix and the corresponding KeyType.
// Returns an error if the key doesn't start with any known prefix.
// Legacy sg_live_ keys map to KeyTypeMerchant.
func detectPrefix(key string) (string, KeyType, error) {
	switch {
	case strings.HasPrefix(key, KeyPrefixAgents):
		return KeyPrefixAgents, KeyTypeAgent, nil
	case strings.HasPrefix(key, KeyPrefixMerchants):
		return KeyPrefixMerchants, KeyTypeMerchant, nil
	case strings.HasPrefix(key, KeyPrefixLive):
		return KeyPrefixLive, KeyTypeMerchant, nil
	default:
		return "", "", fmt.Errorf("API key must start with %s, %s, or %s",
			KeyPrefixMerchants, KeyPrefixAgents, KeyPrefixLive)
	}
}

// ValidateAPIKeyFormat validates that an API key follows the expected format and
// returns the KeyType of the key.
//
// Accepts three prefixes:
//   - "sg_live_"      → KeyTypeMerchant (legacy, kept for backward compat indefinitely)
//   - "sg_merchants_" → KeyTypeMerchant (new merchant keys)
//   - "sg_agents_"    → KeyTypeAgent    (new agent keys)
func ValidateAPIKeyFormat(key string) (KeyType, error) {
	if key == "" {
		return "", fmt.Errorf("API key cannot be empty")
	}

	prefix, keyType, err := detectPrefix(key)
	if err != nil {
		return "", err
	}

	// Extract the portion after prefix
	afterPrefix := strings.TrimPrefix(key, prefix)

	// Split by underscore: keyID_randomPart
	parts := strings.Split(afterPrefix, "_")
	if len(parts) != 2 {
		return "", fmt.Errorf("API key must have format: prefix_keyID_randomPart")
	}

	keyIDPart := parts[0]
	randomPart := parts[1]

	// Check key ID length
	if len(keyIDPart) != KeyIDLength {
		return "", fmt.Errorf("API key ID must be %d characters", KeyIDLength)
	}

	// Check that key ID is valid hex
	if _, err := hex.DecodeString(keyIDPart); err != nil {
		return "", fmt.Errorf("API key ID must be valid hexadecimal")
	}

	// Check random part length
	if len(randomPart) != KeyRandomLength {
		return "", fmt.Errorf("API key random part must be %d characters", KeyRandomLength)
	}

	// Check that random part is valid hex
	if _, err := hex.DecodeString(randomPart); err != nil {
		return "", fmt.Errorf("API key random part must be valid hexadecimal")
	}

	return keyType, nil
}

// ExtractKeyID extracts the key_id from a full API key for database lookup.
// Works for all three accepted prefixes (sg_live_, sg_merchants_, sg_agents_).
func ExtractKeyID(fullKey string) (string, error) {
	if _, err := ValidateAPIKeyFormat(fullKey); err != nil {
		return "", fmt.Errorf("invalid API key format: %w", err)
	}

	prefix, _, err := detectPrefix(fullKey)
	if err != nil {
		return "", fmt.Errorf("invalid key format: %w", err)
	}

	parts := strings.Split(strings.TrimPrefix(fullKey, prefix), "_")
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid key format")
	}
	keyID := parts[0]

	if len(keyID) != KeyIDLength {
		return "", fmt.Errorf("invalid key ID length: expected %d, got %d", KeyIDLength, len(keyID))
	}

	return keyID, nil
}
