package auth

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// KeyType represents the kind of principal a key authenticates.
type KeyType string

const (
	KeyTypeMerchant KeyType = "merchant"
	KeyTypeAgent    KeyType = "agent"
)

// API key format: <prefix><8-char hex keyID>_<32-char hex random>.
//
// KeyPrefixLive is the original merchant prefix, accepted by ValidateAPIKeyFormat for
// backward compatibility but never freshly generated by GenerateAPIKey.
const (
	KeyPrefixLive      = "sg_live_"
	KeyPrefixMerchants = "sg_merchants_"
	KeyPrefixAgents    = "sg_agents_"

	KeyIDLength     = 8
	KeyRandomLength = 32
)

// GenerateAPIKey generates a new API key with embedded key_id like GitHub.
// Returns the full key and the key_id.
//
// keyType determines the prefix:
//   - KeyTypeMerchant → "sg_merchants_"
//   - KeyTypeAgent    → "sg_agents_"
//
// Legacy "sg_live_" keys are never generated by this function but remain accepted by
// ValidateAPIKeyFormat for backward compatibility.
func GenerateAPIKey(keyType KeyType) (string, string, error) {
	prefix, err := prefixForKeyType(keyType)
	if err != nil {
		return "", "", err
	}

	// Generate 8-char key ID for database lookup (4 bytes -> 8 hex chars)
	keyIDBytes := make([]byte, KeyIDLength/2)
	if _, err := rand.Read(keyIDBytes); err != nil {
		return "", "", fmt.Errorf("failed to generate key ID: %w", err)
	}
	keyID := hex.EncodeToString(keyIDBytes)

	// Generate 32 random bytes for the secret portion
	randomBytes := make([]byte, KeyRandomLength/2)
	if _, err := rand.Read(randomBytes); err != nil {
		return "", "", fmt.Errorf("failed to generate random key: %w", err)
	}
	randomStr := hex.EncodeToString(randomBytes)

	// Construct full key: prefix + keyID + randomStr
	fullKey := prefix + keyID + "_" + randomStr
	return fullKey, keyID, nil
}

// prefixForKeyType returns the prefix string for a given KeyType.
// Note: KeyPrefixLive is intentionally not returned — legacy keys are validated but
// never freshly generated.
func prefixForKeyType(t KeyType) (string, error) {
	switch t {
	case KeyTypeMerchant:
		return KeyPrefixMerchants, nil
	case KeyTypeAgent:
		return KeyPrefixAgents, nil
	default:
		return "", fmt.Errorf("unknown key type: %q", t)
	}
}

// detectPrefix returns the matching known prefix and the corresponding KeyType.
// Returns an error if the key doesn't start with any known prefix.
// Legacy sg_live_ keys map to KeyTypeMerchant.
func detectPrefix(key string) (string, KeyType, error) {
	switch {
	case strings.HasPrefix(key, KeyPrefixAgents):
		return KeyPrefixAgents, KeyTypeAgent, nil
	case strings.HasPrefix(key, KeyPrefixMerchants):
		return KeyPrefixMerchants, KeyTypeMerchant, nil
	case strings.HasPrefix(key, KeyPrefixLive):
		return KeyPrefixLive, KeyTypeMerchant, nil
	default:
		return "", "", fmt.Errorf("API key must start with %s, %s, or %s",
			KeyPrefixMerchants, KeyPrefixAgents, KeyPrefixLive)
	}
}

// parseAPIKey validates an API key's format and returns its type, matched prefix, and keyID.
// Named returns let early-exit error paths use bare `return` instead of the noisy
// `return "", "", "", err` pattern.
func parseAPIKey(key string) (keyType KeyType, prefix string, keyID string, err error) {
	if key == "" {
		err = fmt.Errorf("API key cannot be empty")
		return
	}

	prefix, keyType, err = detectPrefix(key)
	if err != nil {
		return
	}

	// Body after prefix: keyID_randomPart
	parts := strings.Split(strings.TrimPrefix(key, prefix), "_")
	if len(parts) != 2 {
		err = fmt.Errorf("API key must have format: prefix_keyID_randomPart")
		return
	}
	keyIDPart, randomPart := parts[0], parts[1]

	if len(keyIDPart) != KeyIDLength {
		err = fmt.Errorf("API key ID must be %d characters", KeyIDLength)
		return
	}
	if _, decodeErr := hex.DecodeString(keyIDPart); decodeErr != nil {
		err = fmt.Errorf("API key ID must be valid hexadecimal")
		return
	}

	if len(randomPart) != KeyRandomLength {
		err = fmt.Errorf("API key random part must be %d characters", KeyRandomLength)
		return
	}
	if _, decodeErr := hex.DecodeString(randomPart); decodeErr != nil {
		err = fmt.Errorf("API key random part must be valid hexadecimal")
		return
	}

	keyID = keyIDPart
	return
}

// ValidateAPIKeyFormat validates an API key's format and returns its KeyType.
// Thin wrapper over parseAPIKey.
func ValidateAPIKeyFormat(key string) (KeyType, error) {
	keyType, _, _, err := parseAPIKey(key)
	return keyType, err
}

// ExtractKeyID extracts the key_id from a full API key for database lookup.
// Works for all three accepted prefixes. Thin wrapper over parseAPIKey.
func ExtractKeyID(fullKey string) (string, error) {
	_, _, keyID, err := parseAPIKey(fullKey)
	if err != nil {
		return "", fmt.Errorf("invalid API key format: %w", err)
	}
	return keyID, nil
}
